language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm@6.2.0
  - npm install codecov -g
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - codecov
cache:
  directories:
    - "$HOME/.npm"
